version: "3.8"

services:

  mongo:
    image: mongo:6
    container_name: proshop-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/quiat/WebstormProjects/proshop-v2/tp:/data/db
    networks:
      - proshop-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: proshop-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://mongo:27017/proshop
      JWT_SECRET: abc123
      PAYPAL_CLIENT_ID: sb
    depends_on:
      - mongo
    networks:
      - proshop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proshop-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - proshop-network

  prometheus:
    image: prom/prometheus:latest
    container_name: proshop-prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - proshop-network

  grafana:
    image: grafana/grafana:latest
    container_name: proshop-grafana
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - proshop-network

volumes:
  grafana-storage:

networks:
  proshop-network:
    driver: bridge